export const Images = {
  Logo: require("./ftslogo.png"),
  Google: require("./google.png"),
  FB: require("./facebook.png"),
  Twitter: require("./twitter.png"),
  Banner: require("./banner.jpg"),
  Courses: require("./courses.png"),
  Students:require("./students.png"),
  Placements:require("./placements.png"),
  ALearners: require("./global-education.jpg"),
  ACourses : require("./Courses-courses.jpg"),
  AAwards:require("./Courses-award.jpg"),
  AEnroll :require("./Courses-survey1.jpg"),
  Fullstact:require("./fullstack.jpg"),
  React:require("./reactjs.jpg"),
  Node:require("./nodejs.jpg"),
  Java:require("./java.png"),
  BIndustry:require("./trained-1.jpg"),
  BPlacements :require("./100-placement.jpg"),
  BIndividual :require("./individual.jpg"),
  BCertificate:require("./certificate.png"),
  BVarioustech:require("./various-tech.png"),
  BLivetech:require("./live-technology.png"),
  Contact :require("./contact-us.jpg"),
  AdminProfile :require("./adminprofile.png"),
};
